--[[
        © AsterionStaff 2022.
        This script was created from the developers of the Asterion Staff.
        You can get more information from one of the links below:
            Site - https://asterion.games
            Discord - https://discord.gg/Np5evb5ZsR
        
        developer(s):
            Selenter - https://steamcommunity.com/id/selenter

        ——— Chop your own wood and it will warm you twice.
]]--

-- Счёт начинается с тройки, ибо    
local offset = 4
for i = offset, #Character.team.instances do
	local v = Character.team.instances[i]
	local id = v.uniqueID
	Print(i, v.uniqueID)
	Character.emoji:Register(id, {
		["#classtrial_sprite_category_main"] = Character.emoji:GetMontedEmojies(id)
	})
end

-- -- TRIGGER HAPPY HAVOC
-- Character.emoji:Register("aoi", {
-- 	["#classtrial_sprite_category_main"] = Character.emoji:GetMontedEmojies("aoi")
-- })

-- Character.emoji:Register("byakuya", {
-- 	["#classtrial_sprite_category_main"] = Character.emoji:GetMontedEmojies("byakuya")
-- })

-- Character.emoji:Register("celestia", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png"
-- 	}
-- })

-- Character.emoji:Register("chihiro", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png"
-- 	}
-- })

-- Character.emoji:Register("hifumi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png"
-- 	}
-- })

-- Character.emoji:Register("junko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png"
-- 	}
-- })

-- Character.emoji:Register("kiyotaka", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("kyoko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png"
-- 	}
-- })

-- Character.emoji:Register("leon", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png"
-- 	}
-- })

-- Character.emoji:Register("makoto", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png"
-- 	}
-- })

-- Character.emoji:Register("mondo", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png"
-- 	}
-- })

-- Character.emoji:Register("sakura", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png"
-- 	}
-- })

-- Character.emoji:Register("sayaka", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png"
-- 	}
-- })

-- Character.emoji:Register("toko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png"
-- 	}
-- })

-- Character.emoji:Register("yasuhiro", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png"
-- 	}
-- })


-- -- GOODBYE DESPAIR
-- Character.emoji:Register("akane", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png"
-- 	}
-- })

-- Character.emoji:Register("chiaki", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png"
-- 	}
-- })

-- Character.emoji:Register("fuyuhiko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png"
-- 	}
-- })

-- Character.emoji:Register("gundham", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png"
-- 	}
-- })

-- Character.emoji:Register("hajime", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("hiyoko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("ibuki", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png"
-- 	}
-- })

-- Character.emoji:Register("kazuichi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png"
-- 	}
-- })

-- Character.emoji:Register("mahiru", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png"
-- 	}
-- })

-- Character.emoji:Register("mikan", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("nagito", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png"
-- 	}
-- })

-- Character.emoji:Register("nekomaru", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png"
-- 	}
-- })

-- Character.emoji:Register("peko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png"
-- 	}
-- })

-- Character.emoji:Register("sonia", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("teruteru", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png"
-- 	}
-- })

-- Character.emoji:Register("twogami", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png"
-- 	}
-- })


-- -- KILLING HARMONY
-- Character.emoji:Register("angie", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png"
-- 	}
-- })

-- Character.emoji:Register("gonta", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png"
-- 	}
-- })

-- Character.emoji:Register("himiko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png"
-- 	}
-- })

-- Character.emoji:Register("k1b0", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png"
-- 	}
-- })

-- Character.emoji:Register("kaede", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png",
-- 		"43.png",
-- 		"44.png",
-- 		"45.png",
-- 		"46.png",
-- 		"47.png"
-- 	}
-- })

-- Character.emoji:Register("kaito", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png",
-- 		"43.png",
-- 		"44.png",
-- 		"45.png"
-- 	}
-- })

-- Character.emoji:Register("kirumi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png"
-- 	}
-- })

-- Character.emoji:Register("kokichi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png"
-- 	}
-- })

-- Character.emoji:Register("korekiyo", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png"
-- 	}
-- })

-- Character.emoji:Register("maki", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png",
-- 		"43.png",
-- 		"44.png",
-- 		"45.png",
-- 		"46.png",
-- 		"47.png",
-- 		"48.png",
-- 		"49.png",
-- 		"50.png",
-- 		"51.png",
-- 		"52.png",
-- 		"53.png"
-- 	}
-- })

-- Character.emoji:Register("miu", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png"
-- 	}
-- })

-- Character.emoji:Register("rantaro", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png"
-- 	}
-- })

-- Character.emoji:Register("ryoma", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png"
-- 	}
-- })

-- Character.emoji:Register("shuichi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png",
-- 		"43.png",
-- 		"44.png",
-- 		"45.png",
-- 		"46.png",
-- 		"47.png",
-- 		"48.png",
-- 		"49.png",
-- 		"50.png",
-- 		"51.png",
-- 		"52.png",
-- 		"53.png",
-- 		"54.png",
-- 		"55.png",
-- 		"56.png",
-- 		"57.png",
-- 		"58.png",
-- 		"59.png",
-- 		"60.png",
-- 		"61.png",
-- 		"62.png",
-- 		"63.png",
-- 		"64.png",
-- 		"65.png",
-- 		"66.png",
-- 		"67.png",
-- 		"68.png",
-- 		"69.png",
-- 		"70.png",
-- 		"71.png",
-- 		"72.png",
-- 		"73.png",
-- 		"74.png",
-- 		"75.png",
-- 		"76.png",
-- 		"77.png",
-- 		"78.png"
-- 	}
-- })

-- Character.emoji:Register("tenko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png"
-- 	}
-- })

-- Character.emoji:Register("tsumugi", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png"
-- 	}
-- })


-- -- ULTRA DESPAIR GIRLS
-- Character.emoji:Register("jataro", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png"
-- 	}
-- })

-- Character.emoji:Register("komaru", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png"
-- 	}
-- })

-- Character.emoji:Register("kotoko", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png"
-- 	}
-- })

-- Character.emoji:Register("masaru", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png"
-- 	}
-- })

-- Character.emoji:Register("monaca", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png"
-- 	},
-- 	["#classtrial_sprite_category_monaca_inwheelchair"] = {
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png",
-- 		"37.png",
-- 		"38.png",
-- 		"39.png",
-- 		"40.png",
-- 		"41.png",
-- 		"42.png"
-- 	}
-- })

-- Character.emoji:Register("nagisa", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png"
-- 	}
-- })


-- -- Ведущие
-- Character.emoji:Register("monokuma", {
-- 	["#classtrial_sprite_category_main"] = {
-- 		"1.png",
-- 		"2.png",
-- 		"3.png",
-- 		"4.png",
-- 		"5.png",
-- 		"6.png",
-- 		"7.png",
-- 		"8.png",
-- 		"9.png",
-- 		"10.png",
-- 		"11.png",
-- 		"12.png",
-- 		"13.png",
-- 		"14.png",
-- 		"15.png",
-- 		"16.png",
-- 		"17.png",
-- 		"18.png",
-- 		"19.png",
-- 		"20.png",
-- 		"21.png",
-- 		"22.png",
-- 		"23.png",
-- 		"24.png",
-- 		"25.png",
-- 		"26.png",
-- 		"27.png",
-- 		"28.png",
-- 		"29.png",
-- 		"30.png",
-- 		"31.png",
-- 		"32.png",
-- 		"33.png",
-- 		"34.png",
-- 		"35.png",
-- 		"36.png"
-- 	}
-- })


-- -- Уникальные