local data = {
	base_picklock = {
		skeletonkey = {
			name = "#item_skeletonkey_name",
			description = "#item_skeletonkey_description",
			model = "models/union/props/lockpick.mdl",
			icon = "danganronpa/inventory/items/artifact_skeletonkey_1.png",
			hacktime = 0,
			maxuse = 999,
		},
		picklock = {
			name = "#item_picklock_name",
			description = "#item_picklock_description",
			model = "models/union/props/lockpick.mdl",
			icon = "https://cdn-icons-png.flaticon.com/512/669/669087.png",
			hacktime = 15,
			maxuse = 2,
		},
	},
	base_ammo = {
		sniper = {
			name = "#item_sniper_name",
			description = "#item_sniper_description",
			model = "models/items/sniper_round_box.mdl",
			ammoClass = "SniperPenetratedRound",
			ammoAmount = 10,
			icon = "https://cdn-icons-png.flaticon.com/512/1614/1614994.png",
		},
		gas = {
			name = "#item_gas_name",
			description = "#item_gas_description",
			model = "models/props_junk/metalgascan.mdl",
			ammoClass = "gasoline",
			ammoAmount = 100,
			icon = "https://cdn-icons-png.flaticon.com/512/6380/6380486.png",
		},
		pistol = {
			name = "#item_pistol_name",
			description = "#item_pistol_description",
			model = "models/items/boxsrounds.mdl",
			ammoClass = "pistol",
			ammoAmount = 15,
			icon = "https://cdn-icons-png.flaticon.com/512/884/884473.png",
		},
		ar2 = {
			name = "#item_ar2_name",
			description = "#item_ar2_description",
			model = "models/items/combine_rifle_cartridge01.mdl",
			ammoClass = "ar2",
			ammoAmount = 40,
			icon = "https://cdn-icons-png.flaticon.com/512/238/238516.png",
		},
		smg1 = {
			name = "#item_smg1_name",
			description = "#item_smg1_description",
			model = "models/items/boxmrounds.mdl",
			ammoClass = "smg1",
			ammoAmount = 40,
			icon = "https://cdn-icons-png.flaticon.com/512/7675/7675032.png",
		},
		["357"] = {
			name = "#item_357_name",
			description = "#item_357_description",
			model = "models/items/357ammo.mdl",
			ammoClass = "357",
			ammoAmount = 6,
			icon = "https://cdn-icons-png.flaticon.com/512/4611/4611320.png",
		},
		buckshot = {
			name = "#item_buckshot_name",
			description = "#item_buckshot_description",
			model = "models/items/boxbuckshot.mdl",
			ammoClass = "buckshot",
			ammoAmount = 7,
			icon = "https://cdn-icons-png.flaticon.com/512/8572/8572145.png",
		},
	},
	base_medical = {
		biogel = {
			name = "#item_biogel_name",
			description = "#item_biogel_description",
			icon = "danganronpa/inventory/items/health_small_biogel.png",
			model = "models/healthvial.mdl",
			maxuse = 2,
			sound = "items/medshot4.wav",
			health = 15,
		},
		medkit = {
			name = "#item_medkit_name",
			description = "#item_medkit_description",
			icon = "danganronpa/inventory/items/health_big_biogel.png",
			model = "models/Items/HealthKit.mdl",
			maxuse = 3,
			sound = "items/medshot4.wav",
			health = 30,
		},
		tablets = {
			name = "#item_tablets_name",
			description = "#item_tablets_description",
			icon = "https://cdn-icons-png.flaticon.com/512/3567/3567506.png",
			model = "models/w_models/weapons/w_eq_painpills.mdl",
			maxuse = 5,
			sound = "items/medshot4.wav",
			health = 10,
		},
		painkillers = {
			name = "#item_painkillers_name",
			description = "#item_painkillers_description",
			icon = "https://cdn-icons-png.flaticon.com/512/1686/1686545.png",
			model = "models/w_models/weapons/w_eq_painpills.mdl",
			maxuse = 5,
			sound = "items/medshot4.wav",
			health = 20,
		},
		sleepingpills = {
			name = "#item_sleepingpills_name",
			description = "#item_sleepingpills_description",
			icon = "https://i.imgur.com/QAuMmpG.png",
			model = "models/w_models/weapons/w_eq_painpills.mdl",
			maxuse = 1,
			sethealth = 0,
			sound = "items/medshot4.wav",
		},
		bandage = {
			name = "#item_bandage_name",
			description = "#item_bandage_description",
			icon = "https://i.imgur.com/clg30oB.png",
			model = "models/union/props/bandage.mdl",
			maxuse = 1,
			sethealth = 35,
			sound = "items/medshot4.wav",
		},
	},
	base_note = {
		newspaper = {
			name = "#item_newspaper_name",
			description = "#item_newspaper_description",
			icon = "https://cdn-icons-png.flaticon.com/512/1566/1566566.png",
			model = "models/foodnhouseholditems/newspaper1.mdl",
		},
		notepad = {
			name = "#item_notepad_name",
			description = "#item_notepad_description",
			icon = "danganronpa/inventory/items/special_papernotebook.png",
			model = "models/props_vtmb/dayplanner_closed.mdl",
		},
		document = {
			name = "#item_document_name",
			description = "#item_document_description",
			icon = "https://cdn-icons-png.flaticon.com/512/1302/1302002.png",
			model = "models/props_vtmb/dayplanner.mdl",
		},
		book1 = {
			name = "#item_book1_name",
			description = "#item_book1_description",
			icon = "https://i.imgur.com/Mtye8xI.png",
			model = "models/props_lab/bindergraylabel01a.mdl",
		},
		paper = {
			name = "#item_paper_name",
			description = "#item_paper_description",
			icon = "https://i.imgur.com/yR4aw4i.png",
			model = "models/foodnhouseholditems/newspaper1.mdl",
		},
	},
	base_weapon = {
		flashlight = {
			name = "#item_flashlight_name",
			description = "#item_flashlight_description",
			model = "models/weapons/w_flashlight_zm.mdl",
			icon = "https://cdn-icons-png.flaticon.com/512/3068/3068819.png",
			class = "academy_flashlight",
			hooks = {
				unequip = function(item, client)
					Flashlight:RemovePlayerFlashlight(client)
				end
			}
		},
		extinguisher = {
			name = "#item_extinguisher_name",
			description = "#item_extinguisher_description",
			model = "models/weapons/w_fire_extinguisher.mdl",
			icon = "https://cdn-icons-png.flaticon.com/512/3183/3183140.png",
			class = "weapon_extinguisher_infinite"
		},
		nightvision = {
			name = "#item_nightvision_name",
			description = "#item_nightvision_description",
			model = "models/weapons/cbinocularsbp/w_nvbinoculars.mdl",
			icon = "danganronpa/inventory/items/special_nvg.png",
			class = "nightvision"
		},
		camera = {
			name = "#item_camera_name",
			description = "#item_camera_description",
			model = "models/MaxOfS2D/camera.mdl",
			icon = "danganronpa/inventory/items/special_polaroid.png",
			class = "academy_camera"
		},
		nmrih_asaw = {
			name = "#item_nmrih_asaw_name",
			description = "#item_nmrih_asaw_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_abrasivesaw.mdl",
			icon = "vgui/entities/tfa_nmrih_asaw",
			class = "tfa_nmrih_asaw"
		},
		nmrih_bat = {
			name = "#item_nmrih_bat_name",
			description = "#item_nmrih_bat_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_bat_metal.mdl",
			icon = "danganronpa/inventory/items/wep_baseballbat.png",
			class = "tfa_nmrih_bat"
		},
		nmrih_chainsaw = {
			name = "#item_nmrih_chainsaw_name",
			description = "#item_nmrih_chainsaw_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_chainsaw.mdl",
			icon = "vgui/entities/tfa_nmrih_chainsaw",
			class = "tfa_nmrih_chainsaw"
		},
		nmrih_bcd = {
			name = "#item_nmrih_bcd_name",
			description = "#item_nmrih_bcd_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_tool_barricade.mdl",
			icon = "vgui/entities/tfa_nmrih_bcd",
			class = "tfa_nmrih_bcd"
		},
		nmrih_cleaver = {
			name = "#item_nmrih_cleaver_name",
			description = "#item_nmrih_cleaver_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_cleaver.mdl",
			icon = "vgui/entities/tfa_nmrih_cleaver",
			class = "tfa_nmrih_cleaver"
		},
		nmrih_crowbar = {
			name = "#item_nmrih_crowbar_name",
			description = "#item_nmrih_crowbar_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_crowbar.mdl",
			icon = "vgui/entities/tfa_nmrih_crowbar",
			class = "tfa_nmrih_crowbar"
		},
		nmrih_etool = {
			name = "#item_nmrih_etool_name",
			description = "#item_nmrih_etool_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_etool.mdl",
			icon = "vgui/entities/tfa_nmrih_etool",
			class = "tfa_nmrih_etool"
		},
		nmrih_fireaxe = {
			name = "#item_nmrih_fireaxe_name",
			description = "#item_nmrih_fireaxe_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_axe_fire.mdl",
			icon = "danganronpa/inventory/items/wep_fireaxe.png",
			class = "tfa_nmrih_fireaxe"
		},
		nmrih_fubar = {
			name = "#item_nmrih_fubar_name",
			description = "#item_nmrih_fubar_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_fubar.mdl",
			icon = "vgui/entities/tfa_nmrih_fubar",
			class = "tfa_nmrih_fubar"
		},
		nmrih_hatchet = {
			name = "#item_nmrih_hatchet_name",
			description = "#item_nmrih_hatchet_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_hatchet.mdl",
			icon = "vgui/entities/tfa_nmrih_hatchet",
			class = "tfa_nmrih_hatchet"
		},
		nmrih_kknife = {
			name = "#item_nmrih_kknife_name",
			description = "#item_nmrih_kknife_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_kitknife.mdl",
			icon = "danganronpa/inventory/items/wep_kitchenknife.png",
			class = "tfa_nmrih_kknife"
		},
		nmrih_lpipe = {
			name = "#item_nmrih_lpipe_name",
			description = "#item_nmrih_lpipe_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_pipe_lead.mdl",
			icon = "vgui/entities/tfa_nmrih_lpipe",
			class = "tfa_nmrih_lpipe"
		},
		nmrih_machete = {
			name = "#item_nmrih_machete_name",
			description = "#item_nmrih_machete_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_machete.mdl",
			icon = "vgui/entities/tfa_nmrih_machete",
			class = "tfa_nmrih_machete"
		},
		nmrih_pickaxe = {
			name = "#item_nmrih_pickaxe_name",
			description = "#item_nmrih_pickaxe_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_pickaxe.mdl",
			icon = "vgui/entities/tfa_nmrih_pickaxe",
			class = "tfa_nmrih_pickaxe"
		},
		nmrih_sledge = {
			name = "#item_nmrih_sledge_name",
			description = "#item_nmrih_sledge_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_sledge.mdl",
			icon = "vgui/entities/tfa_nmrih_sledge",
			class = "tfa_nmrih_sledge"
		},
		nmrih_spade = {
			name = "#item_nmrih_spade_name",
			description = "#item_nmrih_spade_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_spade.mdl",
			icon = "vgui/entities/tfa_nmrih_spade",
			class = "tfa_nmrih_spade"
		},
		nmrih_wrench = {
			name = "#item_nmrih_wrench_name",
			description = "#item_nmrih_wrench_description",
			category = "#item_category_gun_melee",
			model = "models/weapons/tfa_nmrih/w_me_wrench.mdl",
			icon = "vgui/entities/tfa_nmrih_wrench",
			class = "tfa_nmrih_wrench"
		},
		nmrih_m92fs = {
			name = "#item_nmrih_m92fs_name",
			description = "#item_nmrih_m92fs_description",
			category = "#item_category_gun_pistol",
			model = "models/weapons/tfa_nmrih/w_fa_m92fs.mdl",
			icon = "vgui/entities/tfa_nmrih_m92fs",
			class = "tfa_nmrih_m92fs"
		},
		nmrih_1911 = {
			name = "#item_nmrih_1911_name",
			description = "#item_nmrih_1911_description",
			category = "#item_category_gun_pistol",
			model = "models/weapons/tfa_nmrih/w_fa_1911.mdl",
			icon = "vgui/entities/tfa_nmrih_1911",
			class = "tfa_nmrih_1911"
		},
		nmrih_g17 = {
			name = "#item_nmrih_g17_name",
			description = "#item_nmrih_g17_description",
			category = "#item_category_gun_pistol",
			model = "models/weapons/tfa_nmrih/w_fa_glock17.mdl",
			icon = "vgui/entities/tfa_nmrih_g17",
			class = "tfa_nmrih_g17"
		},
		nmrih_mkiii = {
			name = "#item_nmrih_mkiii_name",
			description = "#item_nmrih_mkiii_description",
			category = "#item_category_gun_pistol",
			model = "models/weapons/tfa_nmrih/w_fa_mkiii.mdl",
			icon = "vgui/entities/tfa_nmrih_mkiii",
			class = "tfa_nmrih_mkiii"
		},
		nmrih_sw686 = {
			name = "#item_nmrih_sw686_name",
			description = "#item_nmrih_sw686_description",
			category = "#item_category_gun_pistol",
			model = "models/weapons/tfa_nmrih/w_fa_sw686.mdl",
			icon = "vgui/entities/tfa_nmrih_sw686",
			class = "tfa_nmrih_sw686"
		},
		nmrih_m16_ch = {
			name = "#item_nmrih_m16_ch_name",
			description = "#item_nmrih_m16_ch_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_m16a4_carryhandle.mdl",
			icon = "vgui/entities/tfa_nmrih_m16_ch",
			class = "tfa_nmrih_m16_ch"
		},
		nmrih_m16_rt = {
			name = "#item_nmrih_m16_rt_name",
			description = "#item_nmrih_m16_rt_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_m16a4.mdl",
			icon = "vgui/entities/tfa_nmrih_m16_rt",
			class = "tfa_nmrih_m16_rt"
		},
		nmrih_cz = {
			name = "#item_nmrih_cz_name",
			description = "#item_nmrih_cz_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_cz858.mdl",
			icon = "vgui/entities/tfa_nmrih_cz",
			class = "tfa_nmrih_cz"
		},
		nmrih_fal = {
			name = "#item_nmrih_fal_name",
			description = "#item_nmrih_fal_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_fnfal.mdl",
			icon = "vgui/entities/tfa_nmrih_fal",
			class = "tfa_nmrih_fal"
		},
		nmrih_mp5 = {
			name = "#item_nmrih_mp5_name",
			description = "#item_nmrih_mp5_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_mp5.mdl",
			icon = "vgui/entities/tfa_nmrih_mp5",
			class = "tfa_nmrih_mp5"
		},
		nmrih_mac10 = {
			name = "#item_nmrih_mac10_name",
			description = "#item_nmrih_mac10_description",
			category = "#item_category_gun_submachine",
			model = "models/weapons/tfa_nmrih/w_fa_mac10.mdl",
			icon = "vgui/entities/tfa_nmrih_mac10",
			class = "tfa_nmrih_mac10"
		},
		nmrih_sv10 = {
			name = "#item_nmrih_sv10_name",
			description = "#item_nmrih_sv10_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_sv10.mdl",
			icon = "vgui/entities/tfa_nmrih_sv10",
			class = "tfa_nmrih_sv10"
		},
		nmrih_500a = {
			name = "#item_nmrih_500a_name",
			description = "#item_nmrih_500a_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_500a.mdl",
			icon = "vgui/entities/tfa_nmrih_500a",
			class = "tfa_nmrih_500a"
		},
		nmrih_870 = {
			name = "#item_nmrih_870_name",
			description = "#item_nmrih_870_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_870.mdl",
			icon = "vgui/entities/tfa_nmrih_870",
			class = "tfa_nmrih_870"
		},
		nmrih_rug1022 = {
			name = "#item_nmrih_rug1022_name",
			description = "#item_nmrih_rug1022_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_ruger1022.mdl",
			icon = "vgui/entities/tfa_nmrih_rug1022",
			class = "tfa_nmrih_rug1022"
		},
		nmrih_rug1022_25 = {
			name = "#item_nmrih_rug1022_25_name",
			description = "#item_nmrih_rug1022_25_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_ruger1022_25mag.mdl",
			icon = "vgui/entities/tfa_nmrih_rug1022_25",
			class = "tfa_nmrih_rug1022_25"
		},
		nmrih_sako = {
			name = "#item_nmrih_sako_name",
			description = "#item_nmrih_sako_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_sako85.mdl",
			icon = "vgui/entities/tfa_nmrih_sako",
			class = "tfa_nmrih_sako"
		},
		nmrih_jae700 = {
			name = "#item_nmrih_jae700_name",
			description = "#item_nmrih_jae700_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_jae700.mdl",
			icon = "vgui/entities/tfa_nmrih_jae700",
			class = "tfa_nmrih_jae700"
		},
		nmrih_sako_is = {
			name = "#item_nmrih_sako_is_name",
			description = "#item_nmrih_sako_is_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_sako85_ironsights.mdl",
			icon = "vgui/entities/tfa_nmrih_sako_is",
			class = "tfa_nmrih_sako_is"
		},
		nmrih_sks = {
			name = "#item_nmrih_sks_name",
			description = "#item_nmrih_sks_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_sks.mdl",
			icon = "vgui/entities/tfa_nmrih_sks",
			class = "tfa_nmrih_sks"
		},
		nmrih_sks_nb = {
			name = "#item_nmrih_sks_nb_name",
			description = "#item_nmrih_sks_nb_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_sks_nobayo.mdl",
			icon = "vgui/entities/tfa_nmrih_sks_nb",
			class = "tfa_nmrih_sks_nb"
		},
		nmrih_1892 = {
			name = "#item_nmrih_1892_name",
			description = "#item_nmrih_1892_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_win1892.mdl",
			icon = "vgui/entities/tfa_nmrih_1892",
			class = "tfa_nmrih_1892"
		},
		nmrih_superx3 = {
			name = "#item_nmrih_superx3_name",
			description = "#item_nmrih_superx3_description",
			category = "#item_category_gun_other",
			model = "models/weapons/tfa_nmrih/w_fa_superx3.mdl",
			icon = "vgui/entities/tfa_nmrih_superx3",
			class = "tfa_nmrih_superx3"
		},
		tfcss_ak47 = {
			name = "#item_tfcss_ak47_name",
			description = "#item_tfcss_ak47_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_ak47.mdl",
			icon = "vgui/entities/tfcss_ak47",
			class = "tfcss_ak47"
		},
		tfcss_awp = {
			name = "#item_tfcss_awp_name",
			description = "#item_tfcss_awp_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_snip_awp.mdl",
			icon = "vgui/entities/tfcss_awp",
			class = "tfcss_awp"
		},
		tfcss_deagle = {
			name = "#item_tfcss_deagle_name",
			description = "#item_tfcss_deagle_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_deagle.mdl",
			icon = "vgui/entities/tfcss_deagle",
			class = "tfcss_deagle"
		},
		tfcss_dualelites = {
			name = "#item_tfcss_dualelites_name",
			description = "#item_tfcss_dualelites_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_elite.mdl",
			icon = "vgui/entities/tfcss_dualelites",
			class = "tfcss_dualelites"
		},
		tfcss_famas = {
			name = "#item_tfcss_famas_name",
			description = "#item_tfcss_famas_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_famas.mdl",
			icon = "vgui/entities/tfcss_famas",
			class = "tfcss_famas"
		},
		tfcss_fiveseven = {
			name = "#item_tfcss_fiveseven_name",
			description = "#item_tfcss_fiveseven_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_fiveseven.mdl",
			icon = "vgui/entities/tfcss_fiveseven",
			class = "tfcss_fiveseven"
		},
		tfcss_p90 = {
			name = "#item_tfcss_p90_name",
			description = "#item_tfcss_p90_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_smg_p90.mdl",
			icon = "vgui/entities/tfcss_p90",
			class = "tfcss_p90"
		},
		tfcss_g3sg1 = {
			name = "#item_tfcss_g3sg1_name",
			description = "#item_tfcss_g3sg1_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_snip_g3sg1.mdl",
			icon = "vgui/entities/tfcss_g3sg1",
			class = "tfcss_g3sg1"
		},
		tfcss_galil = {
			name = "#item_tfcss_galil_name",
			description = "#item_tfcss_galil_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_galil.mdl",
			icon = "vgui/entities/tfcss_galil",
			class = "tfcss_galil"
		},
		tfcss_glock = {
			name = "#item_tfcss_glock_name",
			description = "#item_tfcss_glock_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_glock18.mdl",
			icon = "vgui/entities/tfcss_glock",
			class = "tfcss_glock"
		},
		tfcss_ump45 = {
			name = "#item_tfcss_ump45_name",
			description = "#item_tfcss_ump45_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_smg_ump45.mdl",
			icon = "vgui/entities/tfcss_ump45",
			class = "tfcss_ump45"
		},
		tfcss_usp = {
			name = "#item_tfcss_usp_name",
			description = "#item_tfcss_usp_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_usp.mdl",
			icon = "vgui/entities/tfcss_usp",
			class = "tfcss_usp"
		},
		tfcss_m249 = {
			name = "#item_tfcss_m249_name",
			description = "#item_tfcss_m249_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_mach_m249para.mdl",
			icon = "vgui/entities/tfcss_m249",
			class = "tfcss_m249"
		},
		tfcss_m3 = {
			name = "#item_tfcss_m3_name",
			description = "#item_tfcss_m3_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_shot_m3super90.mdl",
			icon = "vgui/entities/tfcss_m3",
			class = "tfcss_m3"
		},
		tfcss_m4a1 = {
			name = "#item_tfcss_m4a1_name",
			description = "#item_tfcss_m4a1_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_m4a1.mdl",
			icon = "vgui/entities/tfcss_m4a1",
			class = "tfcss_m4a1"
		},
		tfcss_mac10 = {
			name = "#item_tfcss_mac10_name",
			description = "#item_tfcss_mac10_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_smg_mac10.mdl",
			icon = "vgui/entities/tfcss_mac10",
			class = "tfcss_mac10"
		},
		tfcss_mp5 = {
			name = "#item_tfcss_mp5_name",
			description = "#item_tfcss_mp5_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_smg_mp5.mdl",
			icon = "vgui/entities/tfcss_mp5",
			class = "tfcss_mp5"
		},
		tfcss_p228 = {
			name = "#item_tfcss_p228_name",
			description = "#item_tfcss_p228_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_pist_p228.mdl",
			icon = "vgui/entities/tfcss_p228",
			class = "tfcss_p228"
		},
		tfcss_scout = {
			name = "#item_tfcss_scout_name",
			description = "#item_tfcss_scout_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_snip_scout.mdl",
			icon = "vgui/entities/tfcss_scout",
			class = "tfcss_scout"
		},
		tfcss_sg550 = {
			name = "#item_tfcss_sg550_name",
			description = "#item_tfcss_sg550_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_snip_sg550.mdl",
			icon = "vgui/entities/tfcss_sg550",
			class = "tfcss_sg550"
		},
		tfcss_sg552 = {
			name = "#item_tfcss_sg552_name",
			description = "#item_tfcss_sg552_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_sg552.mdl",
			icon = "vgui/entities/tfcss_sg552",
			class = "tfcss_sg552"
		},
		tfcss_aug = {
			name = "#item_tfcss_aug_name",
			description = "#item_tfcss_aug_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_rif_aug.mdl",
			icon = "vgui/entities/tfcss_aug",
			class = "tfcss_aug"
		},
		tfcss_tmp = {
			name = "#item_tfcss_tmp_name",
			description = "#item_tfcss_tmp_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_smg_tmp.mdl",
			icon = "vgui/entities/tfcss_tmp",
			class = "tfcss_tmp"
		},
		tfcss_xm1014 = {
			name = "#item_tfcss_xm1014_name",
			description = "#item_tfcss_xm1014_description",
			category = "#item_category_gun_css",
			model = "models/weapons/w_shot_xm1014.mdl",
			icon = "vgui/entities/tfcss_xm1014",
			class = "tfcss_xm1014"
		},
		tfcss_ak47_alt = {
			name = "#item_tfcss_ak47_alt_name",
			description = "#item_tfcss_ak47_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_ak47.mdl",
			icon = "vgui/entities/tfcss_ak47_alt",
			class = "tfcss_ak47_alt"
		},
		tfcss_awp_alt = {
			name = "#item_tfcss_awp_alt_name",
			description = "#item_tfcss_awp_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_snip_awp.mdl",
			icon = "vgui/entities/tfcss_awp_alt",
			class = "tfcss_awp_alt"
		},
		tfcss_deagle_alt = {
			name = "#item_tfcss_deagle_alt_name",
			description = "#item_tfcss_deagle_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_pist_deagle.mdl",
			icon = "danganronpa/inventory/items/wep_deserteagle.png",
			class = "tfcss_deagle_alt"
		},
		tfcss_dualelites_alt = {
			name = "#item_tfcss_dualelites_alt_name",
			description = "#item_tfcss_dualelites_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/w_pist_elite.mdl",
			icon = "vgui/entities/tfcss_dualelites_alt",
			class = "tfcss_dualelites_alt"
		},
		tfcss_famas_alt = {
			name = "#item_tfcss_famas_alt_name",
			description = "#item_tfcss_famas_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_famas.mdl",
			icon = "vgui/entities/tfcss_famas_alt",
			class = "tfcss_famas_alt"
		},
		tfcss_fiveseven_alt = {
			name = "#item_tfcss_fiveseven_alt_name",
			description = "#item_tfcss_fiveseven_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_pist_fiveseven.mdl",
			icon = "vgui/entities/tfcss_fiveseven_alt",
			class = "tfcss_fiveseven_alt"
		},
		tfcss_p90_alt = {
			name = "#item_tfcss_p90_alt_name",
			description = "#item_tfcss_p90_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_smg_p90.mdl",
			icon = "vgui/entities/tfcss_p90_alt",
			class = "tfcss_p90_alt"
		},
		tfcss_g3sg1_alt = {
			name = "#item_tfcss_g3sg1_alt_name",
			description = "#item_tfcss_g3sg1_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_snip_g3sg1.mdl",
			icon = "vgui/entities/tfcss_g3sg1_alt",
			class = "tfcss_g3sg1_alt"
		},
		tfcss_galil_alt = {
			name = "#item_tfcss_galil_alt_name",
			description = "#item_tfcss_galil_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_galil.mdl",
			icon = "vgui/entities/tfcss_galil_alt",
			class = "tfcss_galil_alt"
		},
		tfcss_glock_alt = {
			name = "#item_tfcss_glock_alt_name",
			description = "#item_tfcss_glock_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_pist_glock18.mdl",
			icon = "vgui/entities/tfcss_glock_alt",
			class = "tfcss_glock_alt"
		},
		tfcss_ump45_alt = {
			name = "#item_tfcss_ump45_alt_name",
			description = "#item_tfcss_ump45_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_smg_ump45.mdl",
			icon = "vgui/entities/tfcss_ump45_alt",
			class = "tfcss_ump45_alt"
		},
		tfcss_usp_alt = {
			name = "#item_tfcss_usp_alt_name",
			description = "#item_tfcss_usp_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_pist_usp.mdl",
			icon = "vgui/entities/tfcss_usp_alt",
			class = "tfcss_usp_alt"
		},
		tfcss_m249_alt = {
			name = "#item_tfcss_m249_alt_name",
			description = "#item_tfcss_m249_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_mach_m249para.mdl",
			icon = "vgui/entities/tfcss_m249_alt",
			class = "tfcss_m249_alt"
		},
		tfcss_m3_alt = {
			name = "#item_tfcss_m3_alt_name",
			description = "#item_tfcss_m3_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_shot_m3super90.mdl",
			icon = "vgui/entities/tfcss_m3_alt",
			class = "tfcss_m3_alt"
		},
		tfcss_m4a1_alt = {
			name = "#item_tfcss_m4a1_alt_name",
			description = "#item_tfcss_m4a1_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_m4a1.mdl",
			icon = "vgui/entities/tfcss_m4a1_alt",
			class = "tfcss_m4a1_alt"
		},
		tfcss_mac10_alt = {
			name = "#item_tfcss_mac10_alt_name",
			description = "#item_tfcss_mac10_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_smg_mac10.mdl",
			icon = "vgui/entities/tfcss_mac10_alt",
			class = "tfcss_mac10_alt"
		},
		tfcss_mp5_alt = {
			name = "#item_tfcss_mp5_alt_name",
			description = "#item_tfcss_mp5_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_smg_mp5.mdl",
			icon = "vgui/entities/tfcss_mp5_alt",
			class = "tfcss_mp5_alt"
		},
		tfcss_p228_alt = {
			name = "#item_tfcss_p228_alt_name",
			description = "#item_tfcss_p228_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_pist_p228.mdl",
			icon = "vgui/entities/tfcss_p228_alt",
			class = "tfcss_p228_alt"
		},
		tfcss_scout_alt = {
			name = "#item_tfcss_scout_alt_name",
			description = "#item_tfcss_scout_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_snip_scout.mdl",
			icon = "vgui/entities/tfcss_scout_alt",
			class = "tfcss_scout_alt"
		},
		tfcss_sg550_alt = {
			name = "#item_tfcss_sg550_alt_name",
			description = "#item_tfcss_sg550_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_snip_sg550.mdl",
			icon = "vgui/entities/tfcss_sg550_alt",
			class = "tfcss_sg550_alt"
		},
		tfcss_sg552_alt = {
			name = "#item_tfcss_sg552_alt_name",
			description = "#item_tfcss_sg552_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_sg552.mdl",
			icon = "vgui/entities/tfcss_sg552_alt",
			class = "tfcss_sg552_alt"
		},
		tfcss_aug_alt = {
			name = "#item_tfcss_aug_alt_name",
			description = "#item_tfcss_aug_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_rif_aug.mdl",
			icon = "vgui/entities/tfcss_aug_alt",
			class = "tfcss_aug_alt"
		},
		tfcss_tmp_alt = {
			name = "#item_tfcss_tmp_alt_name",
			description = "#item_tfcss_tmp_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_smg_tmp.mdl",
			icon = "vgui/entities/tfcss_tmp_alt",
			class = "tfcss_tmp_alt"
		},
		tfcss_xm1014_alt = {
			name = "#item_tfcss_xm1014_alt_name",
			description = "#item_tfcss_xm1014_alt_description",
			category = "#item_category_gun_css_alt",
			model = "models/weapons/3_shot_xm1014.mdl",
			icon = "vgui/entities/tfcss_xm1014_alt",
			class = "tfcss_xm1014_alt"
		},
	},
	base_food = {
		apple2 = {
			name = "#item_apple2_name",
			description = "#item_apple2_description",
			model = "models/foodnhouseholditems/apple1.mdl",
			icon = "danganronpa/inventory/items/food_applegreen.png",
			thirst = 8,
			hunger = 8,
			maxuse = 4,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
		},
		coffee = {
			name = "#item_coffee_name",
			description = "#item_coffee_description",
			model = "models/themask/scenebuildthemes/groceries/sm_coffee_cup_paper_02.mdl",
			icon = "danganronpa/inventory/items/food_coffee.png",
			thirst = 10,
			hunger = 0,
			maxuse = 1,
			sleep = 100,
			sound = "eating_and_drinking/drinking.wav",
		},
		pivo = {
			name = "#item_pivo_name",
			description = "#item_pivo_description",
			thirst = 20,
			hunger = 0,
			model = "models/props_junk/garbage_glassbottle001a.mdl",
			maxuse = 3,
			sound = "eating_and_drinking/beerbottle.wav",
			icon = "https://i.imgur.com/CXojHn1.png",
			sleep = -10,
		},
		icecream_vanilla = {
			name = "#item_icecream_vanilla_name",
			description = "#item_icecream_vanilla_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open2.mdl",
			maxuse = 6,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/1JWYbxr.png",
		},
		mcd = {
			name = "#item_mcd_name",
			description = "#item_mcd_description",
			thirst = 100,
			hunger = 100,
			model = "models/foodnhouseholditems/mcdmeal2.mdl",
			maxuse = 1,
			sound = "eating_and_drinking/mcd_meal.wav",
			icon = "https://i.imgur.com/JTlnXLQ.png",
			sleep = 0,
		},
		chickenlegdone = {
			name = "#item_chickenlegdone_name",
			description = "#item_chickenlegdone_description",
			thirst = 0,
			hunger = 20,
			model = "models/foodnhouseholditems/meat4.mdl",
			maxuse = 3,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/7yYbIa2.png",
			sleep = 0,
		},
		sweetroll = {
			name = "#item_sweetroll_name",
			description = "#item_sweetroll_description",
			thirst = -3,
			hunger = 8,
			model = "models/foodnhouseholditems/sweetroll.mdl",
			maxuse = 6,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/10dIUs8.png",
			sleep = 0,
		},
		orangejuice = {
			name = "#item_orangejuice_name",
			description = "#item_orangejuice_description",
			thirst = 10,
			hunger = 0,
			model = "models/foodnhouseholditems/juice.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/VdSRSyr.png",
			sleep = 0,
		},
		cola2 = {
			name = "#item_cola2_name",
			description = "#item_cola2_description",
			thirst = 10,
			hunger = 0,
			model = "models/foodnhouseholditems/sodacan02.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/LXFVG1c.png",
			sleep = 0,
		},
		biscuits = {
			name = "#item_biscuits_name",
			description = "#item_biscuits_description",
			thirst = 0,
			hunger = 5,
			model = "models/foodnhouseholditems/digestive2.mdl",
			maxuse = 10,
			sound = "eating_and_drinking/crunchy_double.wav",
			icon = "https://i.imgur.com/3BzGxld.png",
			sleep = 0,
		},
		pineapple = {
			name = "#item_pineapple_name",
			description = "#item_pineapple_description",
			thirst = 20,
			hunger = 6,
			model = "models/foodnhouseholditems/pineapple.mdl",
			maxuse = 6,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/OL7NjVS.png",
		},
		donemeat = {
			name = "#item_donemeat_name",
			description = "#item_donemeat_description",
			thirst = 0,
			hunger = 30,
			model = "models/foodnhouseholditems/meat8.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/795H4Id.png",
			sleep = 0,
		},
		water_can = {
			name = "#item_water_can_name",
			description = "#item_water_can_description",
			thirst = 20,
			hunger = 0,
			model = "models/props_junk/PopCan01a.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/drinking.wav",
			icon = "https://i.imgur.com/rBXZLFR.png",
		},
		nutella = {
			name = "#item_nutella_name",
			description = "#item_nutella_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/nutella.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/3ovdVFG.png",
		},
		cola3 = {
			name = "#item_cola3_name",
			description = "#item_cola3_description",
			thirst = 10,
			hunger = 0,
			model = "models/foodnhouseholditems/sodacan03.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/hICgMUe.png",
			sleep = 0,
		},
		icecream_creme_brulette = {
			name = "#item_icecream_creme_brulette_name",
			description = "#item_icecream_creme_brulette_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open4.mdl",
			maxuse = 6,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/7fWPuQQ.png",
			sleep = 0,
		},
		chips_cheese = {
			name = "#item_chips_cheese_name",
			description = "#item_chips_cheese_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipsdoritos2.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/opKoBkh.png",
			sleep = 0,
		},
		pancakes = {
			name = "#item_pancakes_name",
			description = "#item_pancakes_description",
			thirst = 0,
			hunger = 10,
			model = "models/foodnhouseholditems/pancakes.mdl",
			maxuse = 12,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/Jb9npyA.png",
			sleep = 0,
		},
		icecream_double = {
			name = "#item_icecream_double_name",
			description = "#item_icecream_double_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open1.mdl",
			maxuse = 6,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/PjCYLbS.png",
		},
		tea = {
			name = "#item_tea_name",
			description = "#item_tea_description",
			thirst = 55,
			hunger = 0,
			model = "models/themask/scenebuildthemes/groceries/sm_coffee_cup_paper_02.mdl",
			maxuse = 1,
			sleep = 0,
			sound = "eating_and_drinking/drinking.wav",
			icon = "https://i.imgur.com/Tlipp86.png",
		},
		cola4 = {
			name = "#item_cola4_name",
			description = "#item_cola4_description",
			thirst = 10,
			hunger = 7,
			model = "models/foodnhouseholditems/sodacan06.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/1iIDoR9.png",
			sleep = 0,
		},
		chocolate3 = {
			name = "#item_chocolate3_name",
			description = "#item_chocolate3_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/marabou2.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/IEffEf0.png",
		},
		grape2 = {
			name = "#item_grape2_name",
			description = "#item_grape2_description",
			thirst = 4,
			hunger = 5,
			model = "models/foodnhouseholditems/grapes2.mdl",
			maxuse = 3,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/VGEIqYl.png",
		},
		cheeseburger = {
			name = "#item_cheeseburger_name",
			description = "#item_cheeseburger_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/burgersims2.mdl",
			maxuse = 3,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/RmHKqps.png",
			sleep = 0,
		},
		icecream_pistachio = {
			name = "#item_icecream_pistachio_name",
			description = "#item_icecream_pistachio_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open5.mdl",
			maxuse = 6,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/hAigoxp.png",
		},
		icecream_coconut = {
			name = "#item_icecream_coconut_name",
			description = "#item_icecream_coconut_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open6.mdl",
			maxuse = 6,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/bl5tXDy.png",
		},
		cola5 = {
			name = "#item_cola5_name",
			description = "#item_cola5_description",
			thirst = 10,
			hunger = 0,
			model = "models/foodnhouseholditems/cola_swift2.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/beerbottle.wav",
			icon = "https://i.imgur.com/zbvNkhh.png",
			sleep = 0,
		},
		cookies = {
			name = "#item_cookies_name",
			description = "#item_cookies_description",
			thirst = 0,
			hunger = 5,
			model = "models/foodnhouseholditems/cookies.mdl",
			maxuse = 10,
			sleep = 0,
			sound = "eating_and_drinking/crunchy_double.wav",
			icon = "https://i.imgur.com/lJ6F8gL.png",
		},
		grape3 = {
			name = "#item_grape3_name",
			description = "#item_grape3_description",
			thirst = 4,
			hunger = 5,
			model = "models/foodnhouseholditems/grapes3.mdl",
			maxuse = 9,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/WXcvasL.png",
			sleep = 0,
		},
		cola1 = {
			name = "#item_cola1_name",
			description = "#item_cola1_description",
			thirst = 10,
			hunger = 7,
			model = "models/foodnhouseholditems/sodacan01.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/VIJ8jyu.png",
		},
		cheese2 = {
			name = "#item_cheese2_name",
			description = "#item_cheese2_description",
			thirst = -4,
			hunger = 15,
			model = "models/foodnhouseholditems/cheesewheel2c.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/doxuXbj.png",
			sleep = 0,
		},
		hleb = {
			name = "#item_hleb_name",
			description = "#item_hleb_description",
			thirst = 0,
			hunger = 35,
			model = "models/themask/scenebuildthemes/groceries/bread.mdl",
			maxuse = 3,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/9a41daO.png",
		},
		biscuits_chocolate = {
			name = "#item_biscuits_chocolate_name",
			description = "#item_biscuits_chocolate_description",
			thirst = 0,
			hunger = 5,
			model = "models/foodnhouseholditems/digestive.mdl",
			maxuse = 10,
			sleep = 0,
			sound = "eating_and_drinking/crunchy_double.wav",
			icon = "https://i.imgur.com/w1cgzhI.png",
		},
		peanut_butter = {
			name = "#item_peanut_butter_name",
			description = "#item_peanut_butter_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/peanut_butter.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/nmNgroT.png",
		},
		apple3 = {
			name = "#item_apple3_name",
			description = "#item_apple3_description",
			thirst = 8,
			hunger = 8,
			model = "models/foodnhouseholditems/apple2.mdl",
			maxuse = 4,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/tV3xyau.png",
			sleep = 0,
		},
		chips_diablo = {
			name = "#item_chips_diablo_name",
			description = "#item_chips_diablo_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipsdoritos2.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/6KITuvv.png",
			sleep = 0,
		},
		apple1 = {
			name = "#item_apple1_name",
			description = "#item_apple1_description",
			thirst = 8,
			hunger = 8,
			model = "models/foodnhouseholditems/apple.mdl",
			maxuse = 4,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/ZXZGuaq.png",
		},
		monster_assault = {
			name = "#item_monster_assault_name",
			description = "#item_monster_assault_description",
			thirst = 40,
			hunger = 0,
			model = "models/foodnhouseholditems/sodacanb03.mdl",
			maxuse = 1,
			sleep = 40,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/rpo2Io8.png",
		},
		icecream_strawberry = {
			name = "#item_icecream_strawberry_name",
			description = "#item_icecream_strawberry_description",
			thirst = 12,
			hunger = 5,
			model = "models/foodnhouseholditems/icecream_open3.mdl",
			maxuse = 6,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/d7Id1zu.png",
			sleep = 0,
		},
		grape1 = {
			name = "#item_grape1_name",
			description = "#item_grape1_description",
			thirst = 4,
			hunger = 5,
			model = "models/foodnhouseholditems/grapes1.mdl",
			maxuse = 3,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/X6Xpb9W.png",
		},
		bigburger = {
			name = "#item_bigburger_name",
			description = "#item_bigburger_description",
			thirst = -5,
			hunger = 25,
			model = "models/foodnhouseholditems/chicken_wrap.mdl",
			maxuse = 4,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/ugQN3tL.png",
			sleep = 0,
		},
		monster_low_carb = {
			name = "#item_monster_low_carb_name",
			description = "#item_monster_low_carb_description",
			thirst = 40,
			hunger = 0,
			model = "models/foodnhouseholditems/sodacanb02.mdl",
			maxuse = 1,
			sound = "eating_and_drinking/can.wav",
			icon = "https://i.imgur.com/TTaW0ms.png",
			sleep = 40,
		},
		turkeyy = {
			name = "#item_turkeyy_name",
			description = "#item_turkeyy_description",
			thirst = 0,
			hunger = 25,
			model = "models/foodnhouseholditems/turkey.mdl",
			maxuse = 8,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/3NOasGQ.png",
			sleep = 0,
		},
		crunch1 = {
			name = "#item_crunch1_name",
			description = "#item_crunch1_description",
			thirst = -5,
			hunger = 5,
			model = "models/foodnhouseholditems/applejacks.mdl",
			maxuse = 5,
			sound = "eating_and_drinking/crunchy_double.wav",
			icon = "https://i.imgur.com/an9o0Xl.png",
			sleep = 0,
		},
		mcd2_0 = {
			name = "#item_mcd2_0_name",
			description = "#item_mcd2_0_description",
			thirst = 100,
			hunger = 100,
			model = "models/foodnhouseholditems/mcdmeal.mdl",
			maxuse = 2,
			sleep = 10,
			sound = "eating_and_drinking/mcd_meal.wav",
			icon = "https://i.imgur.com/QzWde5A.png",
		},
		beefnotdone = {
			name = "#item_beefnotdone_name",
			description = "#item_beefnotdone_description",
			thirst = -5,
			hunger = -20,
			model = "models/foodnhouseholditems/meat7.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/ZtZIkqS.png",
		},
		food_melon = {
			name = "#item_food_melon_name",
			description = "#item_food_melon_description",
			thirst = 30,
			hunger = 5,
			model = "models/foodnhouseholditems/watermelon_unbreakable.mdl",
			maxuse = 10,
			sound = "eating_and_drinking/eating_long.wav",
			icon = "https://i.imgur.com/KjYnmb7.png",
			sleep = 0,
		},
		chickenleg = {
			name = "#item_chickenleg_name",
			description = "#item_chickenleg_description",
			thirst = -3,
			hunger = -15,
			model = "models/foodnhouseholditems/meat3.mdl",
			maxuse = 3,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/mSSx9Sv.png",
			sleep = 0,
		},
		chips_sour_cream_onion = {
			name = "#item_chips_sour_cream_onion_name",
			description = "#item_chips_sour_cream_onion_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipslays4.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/bl66MkL.png",
		},
		chips_dull_pickle = {
			name = "#item_chips_dull_pickle_name",
			description = "#item_chips_dull_pickle_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipslays5.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/LxnBtos.png",
			sleep = 0,
		},
		chocolate1 = {
			name = "#item_chocolate1_name",
			description = "#item_chocolate1_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/marabou4.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/YUmP0ei.png",
		},
		hot_dog = {
			name = "#item_hot_dog_name",
			description = "#item_hot_dog_description",
			thirst = 0,
			hunger = 35,
			model = "models/food/hotdog.mdl",
			maxuse = 3,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/Evy9WF4.png",
		},
		chips_bbq = {
			name = "#item_chips_bbq_name",
			description = "#item_chips_bbq_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipslays3.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/wWdQU5o.png",
			sleep = 0,
		},
		chips_wasabi = {
			name = "#item_chips_wasabi_name",
			description = "#item_chips_wasabi_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipsdoritos6.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/WHNG3hk.png",
		},
		cheese1 = {
			name = "#item_cheese1_name",
			description = "#item_cheese1_description",
			thirst = 0,
			hunger = 15,
			model = "models/foodnhouseholditems/cheesewheel1c.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/G76u3jo.png",
		},
		chocolate2 = {
			name = "#item_chocolate2_name",
			description = "#item_chocolate2_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/marabou1.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/0yxblc9.png",
			sleep = 0,
		},
		sguchenka = {
			name = "#item_sguchenka_name",
			description = "#item_sguchenka_description",
			thirst = 0,
			hunger = 20,
			model = "models/union/props/condensed_milk_open.mdl",
			maxuse = 3,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/8oZxpu4.png",
		},
		chocolate4 = {
			name = "#item_chocolate4_name",
			description = "#item_chocolate4_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/marabou3.mdl",
			maxuse = 2,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/j9vF4OR.png",
			sleep = 0,
		},
		egg = {
			name = "#item_egg_name",
			description = "#item_egg_description",
			thirst = 3,
			hunger = 3,
			model = "models/foodnhouseholditems/egg2.mdl",
			maxuse = 1,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/VakLEp9.png",
			sleep = 0,
		},
		sandwich = {
			name = "#item_sandwich_name",
			description = "#item_sandwich_description",
			thirst = -2,
			hunger = 20,
			model = "models/foodnhouseholditems/sandwich.mdl",
			maxuse = 3,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/5v0WG8z.png",
			sleep = 0,
		},
		chips_salty = {
			name = "#item_chips_salty_name",
			description = "#item_chips_salty_description",
			thirst = -5,
			hunger = 15,
			model = "models/foodnhouseholditems/chipsdoritos5.mdl",
			maxuse = 2,
			sleep = 0,
			sound = "eating_and_drinking/chips.wav",
			icon = "https://i.imgur.com/u8iqDtJ.png",
		},
		cakeslice = {
			name = "#item_cakeslice_name",
			description = "#item_cakeslice_description",
			thirst = -2,
			hunger = 12,
			model = "models/foodnhouseholditems/cakeslice1.mdl",
			maxuse = 4,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/vfV3HzA.png",
			sleep = 0,
		},
		pumpkin = {
			name = "#item_pumpkin_name",
			description = "#item_pumpkin_description",
			thirst = 10,
			hunger = 5,
			model = "models/foodnhouseholditems/pumpkin01.mdl",
			maxuse = 5,
			sleep = 0,
			sound = "eating_and_drinking/eating.wav",
			icon = "https://i.imgur.com/XZ7Dgky.png",
		}
	},
	base_bag = {
		standart = {
			name = "#item_standart_name",
			description = "#item_standart_description",
			model = "models/props_junk/garbage_bag001a.mdl",
			maxw = 4,
			maxh = 4,
		},
		backpackk = {
			name = "#item_backpackk_name",
			description = "#item_backpackk_description",
			icon = "https://i.imgur.com/WcxE6po.png",
			model = "models/props_misc/flour_sack-1.mdl",
			maxh = 4,
			maxw = 5,
		},
		suitcase = {
			name = "#item_suitcase_name",
			description = "#item_suitcase_description",
			icon = "https://i.imgur.com/2iZ1llJ.png",
			maxh = 2,
			model = "models/props_c17/suitcase001a.mdl",
			maxw = 4,
		},
		wallet = {
			name = "#item_wallet_name",
			description = "#item_wallet_description",
			icon = "https://i.imgur.com/Bi6jAGg.png",
			maxh = 2,
			model = "models/props_vtmb/wallet.mdl",
			maxw = 2,
		},
	},
	default = {
		prison_lamp = {
			icon = "https://i.imgur.com/Yx8Sr5W.png",
			model = "models/aschool25/lampavezde.mdl",
			name = "Лампа",
			description = "Осветительный электроприбор, который крепится к потолку и способен выполнять функцию единственного источника света при необходимости.",
		},
		kubok = {
			icon = "https://i.imgur.com/mYdqy33.png",
			model = "models/union/props/junk_storage_sovok_servant_4.mdl",
			name = "Призовой кубок",
			description = "Награда, символ победы, признания и достижения высокого уровня в спорте.",
		},
		metalgascan = {
			icon = "https://i.imgur.com/7qGcYZ8.png",
			description = "Пластмассовая емкость, в которой хранится бензин.",
			model = "models/props_junk/metalgascan.mdl",
			name = "Канистра с бензином",
		},
		ballyacu = {
			icon = "https://i.imgur.com/A3ug6ls.png",
			description = "Шар для гадания. Поговаривают, что это обычный кусок пластика (так и есть).",
			model = "models/dav0r/hoverball.mdl",
			name = "Волшебный шар",
		},
		taperecorder = {
			icon = "https://i.imgur.com/qdH2qfg.png",
			description = "Небольшое устройство, предназначенное для записи речи с целью последующего прослушивания.",
			model = "models/props_vtmb/taperecorder.mdl",
			name = "Диктофон",
		},
		cactus = {
			icon = "https://i.imgur.com/x3U54fo.png",
			description = "Колючее многолетнее растение в горшке. Используется для интерьера.",
			model = "models/props_lab/cactus.mdl",
			name = "Кактус",
		},
		can_of_paint = {
			icon = "https://i.imgur.com/9DkTE3A.png",
			description = "Легкая в использовании банка с краской для творчества и ремонта",
			model = "models/props_junk/plasticbucket001a.mdl",
			name = "Банка краски",
		},
		konus = {
			icon = "https://i.imgur.com/ZjRfKau.png",
			description = "Пластмасовое приспособление для временной разметки дорог.",
			model = "models/props_junk/TrafficCone001a.mdl",
			name = "Дорожный конус",
		},
		hlorka = {
			icon = "https://i.imgur.com/JVr6f1e.png",
			model = "models/props_junk/garbage_plasticbottle001a.mdl",
			name = "Хлорка",
			description = "Хлорная известь в виде раствора, используемая как обеззараживающее средство.",
		},
		gromophom = {
			icon = "https://i.imgur.com/uZQ08PZ.png",
			model = "models/sligwolf/grocel/radio/gramophone.mdl",
			name = "Граммофон",
			description = "Механический аппарат воспроизводящий звуки с пластинок",
		},
		toiletpaper  = {
			icon = "https://i.imgur.com/C2747HY.png",
			model = "models/props/interior/toiletpaperroll.mdl",
			name = "Туалетная бумага",
			description = "Трёхслойная белая туалетная бумага с запахом свежести.",
		},
		teddy = {
			icon = "https://i.imgur.com/R0koewf.png",
			model = "models/props_interiors/teddy_bear.mdl",
			name = "Плюшевый мишка",
			description = "Мягкий и плюшевый, главный фанат среди детей",
		},
		CD = {
			icon = "https://i.imgur.com/fKNubIj.png",
			model = "models/props_vtmb/cdcase.mdl",
			name = "Компакт-диск",
			description = "Оптический носитель информации в виде пластикового диска с отверстием в центре. ",
		},
		breenglobe = {
			icon = "https://i.imgur.com/rqsK1f0.png",
			description = "Трехмерное модельное изображение Земли, используемое для обозначения географических местоположений и изучения географических данных.",
			model = "models/props_combine/breenglobe.mdl",
			name = "Глобус",
		},
		frying_pan = {
			icon = "https://i.imgur.com/n0ZkqTO.png",
			model = "models/props_c17/metalPot002a.mdl",
			name = "Сковорода",
			description = "Посуда для жарки, тушения, выпекания и разогрева пищи. Имеет круглую форму и ручку.",
		},
		batteryacc = {
			icon = "https://i.imgur.com/76syQyK.png",
			description = "Важная состовляющая всех механизмов, которые питаются от электричества",
			model = "models/props_lab/tpplugholder_single.mdl",
			name = "Аккумулятор",
		},
		whiteness = {
			icon = "https://i.imgur.com/q9wxPRo.png",
			model = "models/props_junk/garbage_plasticbottle002a.mdl",
			name = "Белизна",
			description = "Бытовое отбеливающее средство на основе гипохлорита натрия.",
		},
		teapot = {
			icon = "https://i.imgur.com/8NQCLJo.png",
			model = "models/props_interiors/pot01a.mdl",
			name = "Чайник",
			description = "Металлическая ёмкость с крышкой, носиком и ручкой, предназначенная для нагрева и кипячения воды.",
		},
		Gibs = {
			icon = "https://i.imgur.com/bey3XAx.png",
			model = "models/Gibs/HGIBS.mdl",
			name = "Череп",
			description = "Костный каркас головы, совокупность костей.",
		},
		salfetki = {
			icon = "https://i.imgur.com/82yHCZs.png",
			model = "models/themask/scenebuildthemes/furniture/hygiene/sm_tissue_box_01.mdl",
			name = "Салфетки",
			description = "Куски тканей или нетканого материала прямоугольной формы, применяющейся в быту и хозяйстве для удаления различных веществ с поверхностей. ",
		},
		metalbucket = {
			icon = "https://i.imgur.com/v23MFTP.png",
			model = "models/props_junk/MetalBucket01a.mdl",
			name = "Ведро",
			description = "Сосуд для хранения жидких и сыпучих материалов и транспортировки их на небольшие расстояния.",
		},
		nastenie_clock = {
			icon = "https://i.imgur.com/013dmev.png",
			model = "models/props_combine/breenclock.mdl",
			name = "Настольные часы",
			description = "Устройство для измерения времени, которое ставится на какую-либо поверхность.",
		},
		doll = {
			icon = "https://i.imgur.com/XUhEjyY.png",
			description = "Предмет используется в качестве игрушки для маленьких детей.",
			model = "models/props_c17/doll01.mdl",
			name = "Кукла",
		},
		padlock  = {
			icon = "https://i.imgur.com/GHJzbmo.png",
			description = "Механическое устройство, устанавливаемое на двери для обеспечения безопасности и защиты от несанкционированного доступа.",
			model = "models/props_vtmb/padlock1.mdl",
			name = "Дверной замок",
		},
		engine_dvigatel = {
			icon = "https://i.imgur.com/wMZHEwl.png",
			description = "Устройство, способное преобразовывать энергию внешних источников в механическую энергию для привода машин, механизмов и других устройств.",
			model = "models/props_c17/TrapPropeller_Engine.mdl",
			name = "Двигатель",
		},
		utyg = {
			icon = "https://i.imgur.com/gnsNwbs.png",
			model = "models/props_downtown/iron.mdl",
			name = "Утюг",
			description = "Элемент бытовой техники для разглаживания складок и заминов на одежде. ",
		},
		guntella = {
			icon = "https://i.imgur.com/FFggY4F.png",
			model = "models/sal/props/gym/prop_barbell_01.mdl",
			name = "Гантель",
			description = "Маленькая гантель весом 3 кг для физических тренировок",
		},
		vaze = {
			icon = "https://i.imgur.com/DtnqcZg.png",
			description = "Элегантная и изысканная ваза, созданная для подчеркивания красоты и утонченности любого интерьера.",
			model = "models/props_c17/lamp001a.mdl",
			name = "Ваза",
		},
		terracotta = {
			icon = "https://i.imgur.com/pT7Da7O.png",
			model = "models/props_junk/terracotta01.mdl",
			name = "Горшок",
			description = "Собирательное название разнообразных, обычно низких устойчивых, керамических сосудов с широким горлом.",
		},
		fish_toy = {
			icon = "https://i.imgur.com/Fnhn5A3.png",
			model = "models/aschool25/mudfish.mdl",
			name = "Фигурка рыбы",
			description = "Декоративная статуэтка, изображающая рыбу. Такие статуэтки могут использоваться для украшения интерьера и считаются популярными талисманами в фэншуй.",
		},
		clock = {
			icon = "https://i.imgur.com/X48HmfS.png",
			description = "Прибор для определения текущего времени суток.",
			model = "models/props_c17/clock01.mdl",
			name = "Часы",
		},
		soap_dispenser = {
			icon = "https://i.imgur.com/cm1icGk.png",
			model = "models/props_interiors/soap_dispenser.mdl",
			name = "Жидкое мыло",
			description = "Косметический продукт, предназначенный для очищения и ухода за кожей.",
		},
		pipidaster = {
			icon = "https://i.imgur.com/Gp5UNdR.png",
			model = "models/props_vtmb/feather_duster.mdl",
			name = "Пипидастр",
			description = "Щётка-метёлка для аккуратного смахивания пыли с разных поверхностей.",
		},
		cup = {
			icon = "https://i.imgur.com/ftAECmu.png",
			description = "Полое изделие различной формы, преимущественно с ручкой, предназначенное для питья.",
			model = "models/props_junk/garbage_coffeemug001a.mdl",
			name = "Кружка",
		},
		Kactrula = {
			icon = "https://i.imgur.com/9aoUQ7f.png",
			model = "models/props_interiors/pot02a.mdl",
			name = "Кастрюля",
			description = "Посуда для приготовления еды на кухонной плите. Имеет плоское дно и прямые борта с двумя короткими ручками, закрывается крышкой.",
		},
		opener = {
			icon = "https://i.imgur.com/EYe5qc5.png",
			model = "models/union/props/tabletop_bottleopener.mdl",
			name = "Открывашка",
			description = "Железное приспособление для открывания крышек, пробок бутылок, жестяных банок и т. п.",
		},
		disc = {
			icon = "https://i.imgur.com/zXCIjhg.png",
			model = "models/props_vtmb/cdcase.mdl",
			name = "Магнитооптический диск",
			description = "Носитель информации, сочетающий свойства оптических и магнитных накопителей.",
		},
		cilitbang = {
			icon = "https://i.imgur.com/aCZCTdl.png",
			model = "models/foodnhouseholditems/cillitbang.mdl",
			name = "Средство для очистки стёкол",
			description = "Моющее средство для эффективного удаления загрязнений, пятен и разводов с окон.",
		},
		shlakablock  = {
			icon = "https://i.imgur.com/kp8B0Br.png",
			description = "Искусственный строительный камень, который получают путём заливки и прессовки смеси из шлака и цемента.",
			model = "models/props_junk/CinderBlock01a.mdl",
			name = "Шлакаблок",
		},
		vent = {
			icon = "https://i.imgur.com/ckWi4lE.png",
			description = "Удобный и портативный карманный вентилятор для быстрого освежения в любой ситуации.",
			model = "models/cfan/dfan.mdl",
			name = "Вентилятор",
		},
		vial_of_mercury  = {
			icon = "https://i.imgur.com/Gp9vEm0.png",
			model = "models/props_junk/glassjug01.mdl",
			name = "Флакон с ртутью",
			description = "Будьте с ним предельно аккуратными,ведь вещество внутри очень ядовито.",
		}
	}
}

local function registerItem(base, id, info)
	if string.Trim(base) == "" or base == "default" then
		base = nil
	end

	if base then
		local prefix = base:gsub("base_", "")
		id = prefix .. "_" .. id
	end

	local hooks = info.hooks
	info.hooks = nil

	local ITEM = ItemBase.GetBase(base)

	for k, v in pairs(info) do
		ITEM[k] = v
	end

	if hooks then
		ITEM.hooks = ITEM.hooks or {}

		for k, v in pairs(hooks) do
			if ITEM.hooks[k] then
				local oldFunc = ITEM.hooks[k]

				ITEM.hooks[k] = function(...)
					v(...)
					oldFunc(...)
				end
			else
				ITEM.hooks[k] = v
			end
		end
	end

	ItemBase:RegisterItem(id, ITEM)
end

for base, stored in pairs(data) do
	for id, info in pairs(stored) do
		registerItem(base, id, info)
	end
end